config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  devise_for :admins
  mount RailsAdmin::Engine => "/admin", as: :rails_admin
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  devise_for :users, skip: :registrations
  devise_scope :user do
    authenticated :user do
      root "courses#index"
      get "/hot", to: "static_pages#hot", as: :hot
      resources :users, except: %i(create destroy) do
        member do
          get :answers, :questions, :tags
          get "/categories/:category_id", to: "users#categories", as: :category
        end
      end
      resources :questions, controller: :posts, only: %i(index)
      get "/questions/tagged/:name", to: "posts#tagged", as: :tagged_questions
      get "/unanswered/tagged/:name", to: "unanswereds#tagged", as: :tagged_unanswered
      resource :unanswered, only: :show
      resource :tags, only: :show do
        collection do
          get :search
        end
      end
      resources :courses, only: :show do
        resources :questions, controller: :posts, only: %i(new create)
        get :details, on: :member
      end
      resources :questions, controller: :posts, except: %i(new create) do
        resources :comments, controller: :question_comments, except: %i(index show new)
        resources :answers, except: %i(index show new) do
          member do
            post :upvote, :downvote
            patch :mark_best_answer, :unmark_best_answer
          end
        end
        member do
          post :upvote, :downvote
        end
      end
      scope "answers/:answer_id", as: :answer do
        resources :comments, controller: :answer_comments, except: %i(index show new)
      end
      resources :notifications, only: %i(index) do
        patch :open, on: :member
        patch :open_all, on: :collection
      end
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  authenticated :admin do
    mount Sidekiq::Web => "/sidekiq"
    root to: redirect("/admin")
  end
  get "*path", to: "application#page_404"
end

app/controllers/question_comments_controller.rb
class QuestionCommentsController < ApplicationController
  before_action :load_question
  before_action :load_comment, except: :create

  def create
    return unless request.xhr?
    @comment = @post.comments.build comment_params.merge!(user_id: current_user.id)
    @result = @comment.save
    respond_format_js
  end

  def edit
    return unless request.xhr?
    respond_format_js
  end

  def update
    return unless request.xhr?
    @result = @comment.update_attributes comment_params
    respond_format_js
  end

  def destroy
    return unless request.xhr?
    @result = @comment.destroy
    respond_format_js
  end

  private

  def load_question
    @post = Post.question.find_by id: params[:question_id]
    authorize! :read, @post
  end

  def load_comment
    @comment = @post.comments.find_by id: params[:id], user: current_user
    authorize! action_name.to_sym, @comment
  end

  def comment_params
    params.require(:comment).permit :text
  end
end

app/views/question_comments/_comment.html.erb
<div class="qa-c-list-item qa-comment" data-qa-c-id="<%= comment.id %>" id="comment-<%= comment.id %>">
  <span class="qa-c-item-avatar-meta">
    <span class="qa-c-item-avatar">
      <%= link_to user_path(comment.user), class: "qa-avatar-link" do %>
        <%= image_tag comment.user.avatar_url(:thumb), class: "img-circle qa-avatar-image" %>
      <% end %>
    </span>
    <span class="qa-c-item-meta">
      <%= link_to "commented", question_path(question, anchor: "comment-#{comment.id}") %>
      <span class="qa-c-item-when">
        <span class="qa-c-item-when-data">
          <span class="published updated">
            <%= content_tag :span, title: comment.created_at, class: "value-title" do %>
              <%= time_ago_in_words comment.created_at %>
            <% end %>
          </span>
        </span>
      </span>
      <span class="qa-c-item-who">
        <span class="qa-c-item-who-pad">by </span>
        <span class="qa-c-item-who-data">
          <span class="vcard author"><%= link_to comment.user.name, user_path(comment.user) %>
          </span>
        </span>
      </span>
    </span>
  </span>
  <div class="qa-c-item-content"><%= comment.text %></div>
  <% if owner_user? comment.user %>
    <div class="qa-c-item-footer">
      <div class="qa-c-item-buttons">
        <div class="pull-right">
          <%= link_to edit_question_comment_path(question, comment), remote: true, class: "qa-btn" do %>
            <i class="fa fa-pencil-square" aria-hidden="true"></i>
          <% end %>
          <%= link_to question_comment_path(question, comment), method: :delete, remote: true, data: {confirm: "Are you sure"},
            class: "qa-btn" do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="qa-c-item-clear">
  </div>
</div>

app/views/question_comments/_edit_form.html.erb
<div id="qa-q-comment-edit" class="qa-c-form">
  <%= form_with model: comment, url: question_comment_path(question, comment), remote: true do |f| %>
    <div class="qa-c-errors"></div>
    <%= f.text_area :text, class: "form-control qa-c-textarea" %>
    <%= f.submit "Save changes", class: "btn btn-primary" %>
    <%= button_tag "Cancel", type: :button, class: "btn btn-default btn-cancel" %>
  <% end %>
</div>

app/views/question_comments/_form.html.erb
<div id="qa-q-comment" class="qa-c-form collapse toggleable">
  <% if current_user %>
    <h2>Your comment on this question:</h2>
    <%= form_with scope: :comment, url: question_comments_path(question), remote: true do |f| %>
      <div class="qa-q-c-errors"></div>
      <%= f.text_area :text, class: "form-control qa-c-textarea" %>
      <%= f.submit "Add comment", class: "btn btn-primary" %>
      <%= button_tag "Cancel", data: {toggle: :collapse, target: "#qa-q-comment"}, type: :button, class: "btn btn-default btn-cancel" %>
    <% end %>
  <% else %>
     <h2>Please <%= link_to "log in", new_user_session_path %> or <%= link_to "register", new_user_registration_path %> to add a comment.</h2>
  <% end %>
</div>

app/views/question_comments/create.js.erb
<% if @result %>
  $('.qa-q-view-c-list').append('<%= j render(partial: "comment", locals: {comment: @comment, question: @post}) %>');
  $('#qa-q-comment').collapse('hide');
  $('#qa-q-comment textarea').val('');
<% else %>
  $('.qa-q-c-errors').html('<%= j render(partial: "shared/error_messages", locals: {object: @comment}) %>');
<% end %>

app/views/question_comments/destroy.js.erb
$('[data-qa-q-c-id="<%= @comment.id %>"]').remove();

app/views/question_comments/edit.js.erb
$('[data-qa-c-id="<%= @comment.id %>"]').html('<%= j render partial: "edit_form", locals: {question: @post, comment: @comment} %>');
$('[data-qa-c-id="<%= @comment.id %>"] .qa-c-textarea').focus();
$('[data-qa-c-id="<%= @comment.id %>"] .btn-cancel').click(function() {
  $('[data-qa-c-id="<%= @comment.id %>"]').replaceWith('<%= j render partial: "comment", locals: {question: @post, comment: @comment} %>');
});

app/views/question_comments/update.js.erb
<% if @result %>
  $('[data-qa-c-id="<%= @comment.id %>"]').replaceWith('<%= j render(partial: "comment", locals: {comment: @comment, question: @post}) %>');
<% else %>
  $('[data-qa-c-id="<%= @comment.id %>"] .qa-q-c-errors').html('<%= j render(partial: "shared/error_messages", locals: {object: @comment}) %>');
<% end %>