config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  devise_for :admins
  mount RailsAdmin::Engine => "/admin", as: :rails_admin
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  devise_for :users, skip: :registrations
  devise_scope :user do
    authenticated :user do
      root "courses#index"
      get "/hot", to: "static_pages#hot", as: :hot
      resources :users, except: %i(create destroy) do
        member do
          get :answers, :questions, :tags
          get "/categories/:category_id", to: "users#categories", as: :category
        end
      end
      resources :questions, controller: :posts, only: %i(index)
      get "/questions/tagged/:name", to: "posts#tagged", as: :tagged_questions
      get "/unanswered/tagged/:name", to: "unanswereds#tagged", as: :tagged_unanswered
      resource :unanswered, only: :show
      resource :tags, only: :show do
        collection do
          get :search
        end
      end
      resources :courses, only: :show do
        resources :questions, controller: :posts, only: %i(new create)
        get :details, on: :member
      end
      resources :questions, controller: :posts, except: %i(new create) do
        resources :comments, controller: :question_comments, except: %i(index show new)
        resources :answers, except: %i(index show new) do
          member do
            post :upvote, :downvote
            patch :mark_best_answer, :unmark_best_answer
          end
        end
        member do
          post :upvote, :downvote
        end
      end
      scope "answers/:answer_id", as: :answer do
        resources :comments, controller: :answer_comments, except: %i(index show new)
      end
      resources :notifications, only: %i(index) do
        patch :open, on: :member
        patch :open_all, on: :collection
      end
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  authenticated :admin do
    mount Sidekiq::Web => "/sidekiq"
    root to: redirect("/admin")
  end
  get "*path", to: "application#page_404"
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :load_question
  before_action :load_answer, except: %i(create)

  def create
    return unless request.xhr?
    @answer = @question.answers.build answer_params.merge! post_type: :answer, owner_user_id: current_user.id
    @result = @answer.save
  end

  def edit
    return unless request.xhr?
    respond_format_js
  end

  def update
    return unless request.xhr?
    @result = @answer.update_attributes answer_params
  end

  def destroy
    if @answer.destroy
      flash[:notice] = "Deleted successful answer"
    else
      flash[:danger] = "Deleted failed answer"
    end
    redirect_to question_url(@question)
  end

  def upvote
    return unless request.xhr?
    @vote = current_user.votes.build post: @answer, vote_type: :up_mod
    @user_vote_value = @answer.vote_value_by current_user
    @result = @vote.save
    respond_format_js
  end

  def downvote
    return unless request.xhr?
    @vote = current_user.votes.build post: @answer, vote_type: :down_mod
    @user_vote_value = @answer.vote_value_by current_user
    @result = @vote.save
    respond_format_js
  end

  def mark_best_answer
    return unless request.xhr?
    @result = @answer.update_attributes best_answer: true, marker: current_user, mark_best_answer_at: Time.current
    respond_format_js
  end

  def unmark_best_answer
    return unless request.xhr?
    @result = @answer.update_attributes best_answer: false, marker: current_user, mark_best_answer_at: nil
    respond_format_js
  end

  private

  def load_question
    @question = Post.question.find_by id: params[:question_id]
    authorize! :read, @question
  end

  def load_answer
    @answer = @question.answers.load_votes.select_posts_votes.find_by id: params[:id]
    authorize! action_name.to_sym, @answer
  end

  def answer_params
    params.require(:post).permit :body
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
  def check_icon_best_answer answer
    return unless current_user.lecturer? || answer.best_answer?
    if current_user.lecturer?
      url = if answer.best_answer?
              unmark_best_answer_question_answer_path(answer.question, answer)
            else
              mark_best_answer_question_answer_path(answer.question, answer)
            end
      link_to url, data: {remote: true, method: :patch} do
        content_tag :div, class: "qa-a-selection check-icon-toggle #{answer.best_answer? ? 'check-open' : nil}",
          title: answer.best_answer_title do
          render partial: "shared/check_icon"
        end
      end
    else
      content_tag :div, class: "qa-a-selection check-icon-toggle check-open", title: answer.best_answer_title do
        render partial: "shared/check_icon"
      end
    end
  end
end

app/views/answers/_edit_form.html.erb
<div id="qa-q-answer" class="collapse toggleable">
  <div class="qa-part-form">
  <h2>Edit your answer</h2>
  <%= form_with scope: :post, model: answer, url: question_answer_path(question) do |f| %>
    <div class="qa-a-errors"></div>
    <div class="form-group">
      <%= f.text_area :body, class: "ckeditor", id: "qa-a-textarea" %>
    </div>
    <%= f.submit "Update answer", class: "btn btn-info" %>
    <%= button_tag "Cancel", data: {toggle: :collapse, target: "#qa-q-answer"}, type: :button, class: "btn btn-default btn-cancel" %>
  <% end %>
  </div>
</div>

app/views/answers/_form.html.erb
<div id="qa-q-answer" class="collapse toggleable">
  <% if current_user %>
    <div class="qa-part-form">
      <h2>Your answer</h2>
      <%= form_with model: new_answer, url: question_answers_path(question), remote: true do |f| %>
        <div class="qa-a-errors"></div>
        <div class="form-group">
          <%= f.text_area :body, class: "ckeditor" %>
        </div>
        <%= f.submit "Add answer", class: "btn btn-info" %>
        <%= button_tag "Cancel", data: {toggle: :collapse, target: "#qa-q-answer"}, type: :button, class: "btn btn-default btn-cancel" %>
      <% end %>
    </div>
  <% else %>
    <h2>
      Please <%= link_to "log in", new_user_session_path %> or <%= link_to "register", new_user_registration_path %> to answer this question.
    </h2>
  <% end %>
</div>

app/views/answers/create.js.erb
<% if @result %>
  window.location.href = '<%= question_url(@question) %>';
<% else %>
  $('#qa-q-answer .qa-a-errors').html('<%= j render(partial: "shared/error_messages", locals: {object: @answer}) %>');
<% end %>

app/views/answers/downvote.js.erb
<% if @result %>
  <% if @user_vote_value == 1 %>
    $('[data-answer-id="<%= @answer.id %>"] .up_mod').removeClass('voting-color');
  <% else %>
    $('[data-answer-id="<%= @answer.id %>"] .down_mod').addClass('voting-color');
  <% end %>
  $('[data-answer-id="<%= @answer.id %>"] .points').html('<%= @answer.vote_count.to_i - 1 %>')
<% else %>
  pnotify('Error!', '<%= @vote.errors.messages[:vote].first %>', 'error');
<% end %>

app/views/answers/edit.js.erb
$('.qa-q-buttons, .qa-btn').remove();
$('#qa-q-answer').replaceWith('<%= j render partial: "edit_form", locals: {answer: @answer, question: @question} %>')
CKEDITOR.replace('qa-a-textarea');
$('#qa-q-answer').collapse('show');
$('.btn-cancel').click(function() {
  window.location.href = '<%= question_url(@question) %>';
});

app/views/answers/mark_best_answer.js.erb
<% if @result %>
  $('[data-qa-q-a-id="<%= @answer.id %>"] .check-icon-toggle').addClass('check-open');
  $('[data-qa-q-a-id="<%= @answer.id %>"] .check-icon-toggle').parent()
    .attr('href', '<%= unmark_best_answer_question_answer_path(@answer.question, @answer) %>');
  $('[data-qa-q-a-id="<%= @answer.id %>"] .check-icon-toggle').attr('title', '<%= @answer.best_answer_title %>');
<% else %>
  pnotify('Error!', '<%= @answer.errors.messages[:best_answer].first %>', 'error');
<% end %>

app/views/answers/unmark_best_answer.js.erb
<% if @result %>
  $('[data-qa-q-a-id="<%= @answer.id %>"] .check-icon-toggle').removeClass('check-open');
  $('[data-qa-q-a-id="<%= @answer.id %>"] .check-icon-toggle').parent()
    .attr('href', '<%= mark_best_answer_question_answer_path(@answer.question, @answer) %>');
  $('[data-qa-q-a-id="<%= @answer.id %>"] .check-icon-toggle').attr('title', '');
<% else %>
  pnotify('Error!', '<%= @answer.errors.messages[:best_answer].first %>', 'error');
<% end %>

app/views/answers/update.js.erb
<% if @result %>
  window.location.href = '<%= question_url(@question) %>';
<% else %>
  $('#qa-q-answer .qa-a-errors').html('<%= j render(partial: "shared/error_messages", locals: {object: @answer}) %>');
<% end %>

app/views/answers/upvote.js.erb
<% if @result %>
  <% if @user_vote_value == -1 %>
    $('[data-answer-id="<%= @answer.id %>"] .down_mod').removeClass('voting-color');
  <% else %>
    $('[data-answer-id="<%= @answer.id %>"] .up_mod').addClass('voting-color');
  <% end %>
  $('[data-answer-id="<%= @answer.id %>"] .points').html('<%= @answer.vote_count.to_i + 1 %>')
<% else %>
  pnotify('Error!', '<%= @vote.errors.messages[:vote].first %>', 'error');
<% end %>