config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  devise_for :admins
  mount RailsAdmin::Engine => "/admin", as: :rails_admin
  mount Ckeditor::Engine => "/ckeditor"
  mount ActionCable.server => "/cable"

  devise_for :users, skip: :registrations
  devise_scope :user do
    authenticated :user do
      root "courses#index"
      get "/hot", to: "static_pages#hot", as: :hot
      resources :users, except: %i(create destroy) do
        member do
          get :answers, :questions, :tags
          get "/categories/:category_id", to: "users#categories", as: :category
        end
      end
      resources :questions, controller: :posts, only: %i(index)
      get "/questions/tagged/:name", to: "posts#tagged", as: :tagged_questions
      get "/unanswered/tagged/:name", to: "unanswereds#tagged", as: :tagged_unanswered
      resource :unanswered, only: :show
      resource :tags, only: :show do
        collection do
          get :search
        end
      end
      resources :courses, only: :show do
        resources :questions, controller: :posts, only: %i(new create)
        get :details, on: :member
      end
      resources :questions, controller: :posts, except: %i(new create) do
        resources :comments, controller: :question_comments, except: %i(index show new)
        resources :answers, except: %i(index show new) do
          member do
            post :upvote, :downvote
            patch :mark_best_answer, :unmark_best_answer
          end
        end
        member do
          post :upvote, :downvote
        end
      end
      scope "answers/:answer_id", as: :answer do
        resources :comments, controller: :answer_comments, except: %i(index show new)
      end
      resources :notifications, only: %i(index) do
        patch :open, on: :member
        patch :open_all, on: :collection
      end
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  authenticated :admin do
    mount Sidekiq::Web => "/sidekiq"
    root to: redirect("/admin")
  end
  get "*path", to: "application#page_404"
end

app/controllers/unanswereds_controller.rb
class UnansweredsController < ApplicationController
  before_action :load_course, :load_course_posts, :load_course_tags

  def show
    unanswered_questions_data = @course_posts.includes(:owner_user, :tags, :answers).question.load_votes
                                             .select_posts_votes.unanswered
    @unanswered_tags = @course_tags.popular.unanswered
    @tab = tab_active "votest", "newest", "votest"
    @unanswered_questions = DataTabPresenter.new(unanswered_questions_data, @tab).load_unanswered_questions
                                            .page(params[:page]).per Settings.paginate.per_page
  end

  def tagged
    unanswered_questions_data = @course_posts.includes(:owner_user, :answers, :tags).question.load_votes.select_posts_votes
                                             .unanswered.load_tag_by_name params[:name]
    @unanswered_tags = @course_tags.popular.unanswered
    @tab = tab_active "votest", "newest", "votest"
    @unanswered_questions = DataTabPresenter.new(unanswered_questions_data, @tab).load_unanswered_questions
                                            .page(params[:page]).per Settings.paginate.per_page
  end
end

app/views/unanswereds/_sidepanel.html.erb
<div class="qa-sidepanel" id="qam-sidepanel-mobile">
  <% if course %>
    <%= link_to "Ask question", new_course_question_path(course), class: "ask btn btn-primary" %>
    <div class="qa-widget-side">
      <div class="section-title-line">
        <%= content_tag :h2, title: "#{course.name} - #{course.course_category.name}" do %>
          <%= course.name.truncate_words 2 %>
        <% end %>
        <hr class="filler-line">
      </div>
      <div>
        <p>Student: <%= course.users.students.size %></p>
        <p>Question: <%= course.posts_count %></p>
        <p>Answer: <%= course.course_answers_count %></p>
      </div>
    </div>
  <% end %>
  <div class="sidebar-box-links">
    <%= link_to hot_path(course_id: course) do %>
      <i class="fa fa-fire" aria-hidden="true"></i> Hot question
    <% end %>
  </div>
  <div class="qa-widget-side">
    <div class="section-title-line"><h2>Unanswered Tags</h2><hr class="filler-line"></div>
    <div>
      <%= render partial: "tag_sidepanel", collection: tags, as: :tag, locals: {course: @course} %>
    </div>
    <div class="sidebar-box-links">
      <%= link_to tags_path(course_id: course) do %>
        <i aria-hidden="true" class="fa fa-tags mr-05"></i> All tags
      <% end %>
    </div>
  </div>
</div>

app/views/unanswereds/_tag_sidepanel.html.erb
<div>
  <%= link_to tag.name, tagged_unanswered_path(tag.name, course_id: course), class: "qa-tag-link" %>
  <span>x <%= tag.tag_count.to_i %></span>
</div>

app/views/unanswereds/show.html.erb
<div class="col-md-3 col-sm-4 col-xs-4 qa-tabs-title">
  <h2>Unanswered Questions</h2>
</div>
<div class="nav-tab-bound">
  <ul class="nav nav-tabs qa-nav-tabs-right">
    <li class="menu-second-top-nav"><%= link_to "All questions", questions_path(course_id: @course), title: "Switch to all questions tabs" %></li>
    <li class="menu-second-top-nav <%= @tab == "newest" ? :active : nil %>">
      <%= link_to "Newest", unanswered_path(tab: :newest, course_id: @course), title: "newest unanswered questions" %>
    </li>
    <li class="menu-second-top-nav <%= @tab == "votest" ? :active : nil %>">
      <%= link_to "Votes", unanswered_path(tab: :votest, course_id: @course), title: "highest voted unanswered questions" %>
    </li>
  </ul>
</div>

<div class="tab-content">
  <div class="qa-main">
    <div class="qa-part-q-list">
      <div class="qa-q-list">
        <%= render partial: "posts/question", collection: @unanswered_questions, locals: {course: @course} %>
        <%= paginate @unanswered_questions, params: {tab: @tab, course_id: @course} %>
      </div>
    </div>
  </div>
  <%= render partial: "sidepanel", locals: {tags: @unanswered_tags, course: @course} %>
</div>

app/views/unanswereds/tagged.html.erb
<div class="container">
  <div class="nav-tab-bound">
    <ul class="nav nav-tabs qa-nav-tabs-right">
    <li><%= link_to "All questions", tagged_questions_path(params[:name], course_id: @course), title: "Switch to all questions tabs" %></li>
    <li class="menu-second-top-nav <%= @tab == "newest" ? :active : nil %>">
      <%= link_to "Newest", tagged_unanswered_path(tab: :newest, course_id: @course), title: "newest unanswered questions" %>
    </li>
    <li class="menu-second-top-nav <%= @tab == "votest" ? :active : nil %>">
      <%= link_to "Votes", tagged_unanswered_path(tab: :votest, course_id: @course), title: "highest voted unanswered questions" %>
    </li>
  </ul>
  </div>

  <div class="tab-content">
    <div class="qa-main">
      <div class="qa-part-q-list">
        <div class="qa-q-list">
          <%= render partial: "posts/question", collection: @unanswered_questions, locals: {course: @course} %>
          <%= paginate @unanswered_questions, params: {tab: @tab, course_id: @course} %>
        </div>
      </div>
    </div>
    <%= render partial: "sidepanel", locals: {tags: @unanswered_tags, course: @course} %>
  </div>
</div>